#name: jclagache
#description: Software Craftsman
logo: /img/header.png

paginate: 5

markdown: rdiscount
# github defaults
highlighter: pygments
# github overwrite
safe: true
lsi: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Paris
encoding: UTF-8

baseurl: "http://jclagache.me"